use async_trait::async_trait;
use serde_json::Value;

/// Represents a prompt template exposed by the MCP server.
#[async_trait]
pub trait Prompt: Send + Sync {
    /// Returns the unique name of the prompt.
    fn name(&self) -> &str;

    /// Returns a description of the prompt.
    fn description(&self) -> Option<&str>;

    /// Returns the list of arguments this prompt accepts.
    fn arguments(&self) -> Vec<PromptArgument>;

    /// Renders the prompt with the given arguments.
    async fn get(&self, args: Value) -> anyhow::Result<GetPromptResult>;
}

/// Argument definition for a prompt.
#[derive(Debug, Clone, serde::Serialize)]
pub struct PromptArgument {
    /// Name of the argument.
    pub name: String,
    /// Description of the argument.
    pub description: Option<String>,
    /// Whether the argument is required.
    pub required: bool,
}

/// Result of getting a prompt.
#[derive(Debug, Clone, serde::Serialize)]
pub struct GetPromptResult {
    /// Description of the prompt result.
    pub description: Option<String>,
    /// Messages generated by the prompt.
    pub messages: Vec<PromptMessage>,
}

/// A message in a prompt.
#[derive(Debug, Clone, serde::Serialize)]
pub struct PromptMessage {
    /// Role of the message sender (e.g., "user", "assistant").
    pub role: String,
    /// Content of the message.
    pub content: PromptMessageContent,
}

/// Content of a prompt message.
#[derive(Debug, Clone, serde::Serialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum PromptMessageContent {
    /// Text content.
    Text {
        /// The text content.
        text: String,
    },
    /// Image content.
    Image {
        /// Base64 encoded image data.
        data: String,
        /// MIME type of the image.
        mime_type: String,
    },
    // Resource { uri: String } - Future extension
}
